### ISSUE TITLE
Xamarin Studio latest update breaks Obliterate Output Paths

### ISSUE THREAD

**Issue by ianjonesau** [Redth/XamarinStudio.RedthsAddin#1]
Looks like MonoDevelop.Core / MonoDevelop.Ide needs to be v6.0.1 (up from v6.0).
![image](https://cloud.githubusercontent.com/assets/5147168/16286997/707e16ac-3923-11e6-8fc6-be4a16c0a8ff.png)
Thanks again - love this plugin!

**Comment by Redth** [comment]
This was fixed awhile back, also recommended to use VS for Mac now of course :)
