### ISSUE TITLE
Redth's addin v1.0.6 update "for XS 6.0.1" requires Xamarin Studio 7.0

### ISSUE THREAD

**Issue by Emasoft** [Redth/XamarinStudio.RedthsAddin#3]
Xamarin Studio (v6.2) prompted me for updating the Redth's addin to v1.0.6, but the new update seems to be for Xamarin Studio 7.0 and not for XS 6.0.1 as indicated. I also tried to download directly the version labelled for XS v6.0.1 from [here](http://addins.monodevelop.com/Project/Index/132), but it is the same. 
![schermata 2017-03-01 alle 14 36 32](https://cloud.githubusercontent.com/assets/713559/23462037/912a9324-fe8c-11e6-8da3-f5fa549ee18b.png)
![schermata 2017-03-01 alle 14 36 17](https://cloud.githubusercontent.com/assets/713559/23462036/9127cc02-fe8c-11e6-88b4-0b6c16c933fa.png)

**Comment by drjackyl** [comment]
+8 from our team :-)

**Comment by marra85** [comment]
Hi All,

I'm also experiencing this issue, but by checking the commit history I was able to find the issue and fix it.
I'm attaching a fixed addin pack it so you can install it from the filesystem and return to obliterate the output paths like there's no tomorrow 😄 
[RedthAddin_1.0.6.zip](https://github.com/Redth/XamarinStudio.RedthsAddin/files/816760/RedthAddin_1.0.6.zip)

**Comment by Emasoft** [comment]
Thank you! 😄

**Comment by drjackyl** [comment]
I saw the problem as well, but I wasn't able to build the add-in alongside daily business. We reverted to a previous version of a colleague who didn't update, yet.
