### ISSUE TITLE
Edit Project File opens first file in project instead of the project file

### ISSUE THREAD

**Issue by mrward** [Redth/XamarinStudio.RedthsAddin#4]
Original bug reported on [bugzilla](https://bugzilla.xamarin.com/show_bug.cgi?id=58086).

Looking at the [code](https://github.com/Redth/XamarinStudio.RedthsAddin/blob/88917ee49c32c0c430ec93131a6376d295c4aff3/RedthAddin/EditProjectFileCommandHandler.cs#L14-L18) it looks like it should be doing something like:

    var item = IdeApp.ProjectOperations.CurrentSelectedProject;
    
    IdeApp.OpenFiles (new [] {
        new FileOpenInformation (item.FileName, item)
    });

**Comment by Redth** [comment]
This is fixed now in v1.0.8
